//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoApi.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.INCRIPCION = new HashSet<INCRIPCION>();
        }
    
        public int ID_CURSO { get; set; }
        public int ID_MATERIA { get; set; }
        public string ID_PROFESOR { get; set; }
    
        public virtual MATERIA MATERIA { get; set; }
        public virtual PROFESOR PROFESOR { get; set; }
        public virtual ICollection<INCRIPCION> INCRIPCION { get; set; }
    }
}
