//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoApi.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCRIPCION
    {
        public int ID_INCRIPCION { get; set; }
        public int ID_CURSO { get; set; }
        public string ID_ALUMNO { get; set; }
        public Nullable<short> NOTA1 { get; set; }
        public Nullable<short> NOTA2 { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
        public virtual CURSO CURSO { get; set; }
    }
}
