//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoApi.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA
    {
        public MATERIA()
        {
            this.CURSO = new HashSet<CURSO>();
        }
    
        public int ID_MATERIA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<CURSO> CURSO { get; set; }
    }
}
