//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoApi.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SINCOABREntities1 : DbContext
    {
        public SINCOABREntities1()
            : base("name=SINCOABREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALUMNO> ALUMNO { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<INCRIPCION> INCRIPCION { get; set; }
        public DbSet<MATERIA> MATERIA { get; set; }
        public DbSet<PROFESOR> PROFESOR { get; set; }
        public DbSet<INCRIPCIONES> INCRIPCIONES { get; set; }
        public DbSet<ALUMNOS> ALUMNOS { get; set; }
        public DbSet<CURSOS> CURSOS { get; set; }
        public DbSet<CURSOS_LIST> CURSOS_LIST { get; set; }
        public DbSet<MATERIAS> MATERIAS { get; set; }
        public DbSet<PROFESORES> PROFESORES { get; set; }
    }
}
