CREATE VIEW INCRIPCIONES
AS
SELECT ID_INCRIPCION, CONCAT(ISNULL(A.NOMBRE, ''), ' ', ISNULL(A.APELLIDO, '')) AS ALUMNO,
M.NOMBRE AS MATERIA,
CONCAT( ISNULL(P.NOMBRE, ''), ' ', ISNULL(P.APELLIDO , ''))  AS PROFESOR, I.NOTA1, I.NOTA2
FROM INCRIPCION I
INNER JOIN ALUMNO A ON A.ID_ALUMNO = I.ID_ALUMNO
INNER JOIN CURSO C ON C.ID_CURSO = I.ID_CURSO
INNER JOIN MATERIA M ON C.ID_MATERIA=M.ID_MATERIA
INNER JOIN PROFESOR P ON C.ID_PROFESOR=P.ID_PROFESOR
GO
CREATE VIEW CURSOS
AS
SELECT C.ID_CURSO, M.NOMBRE AS MATERIA, CONCAT( ISNULL(P.NOMBRE, ''), ' ', ISNULL(P.APELLIDO, '')  ) AS PROFESOR FROM CURSO C
INNER JOIN MATERIA M ON C.ID_MATERIA=M.ID_MATERIA
INNER JOIN PROFESOR P ON C.ID_PROFESOR=P.ID_PROFESOR
GO


